version: "3.9"
services:
  postgres:
    container_name: database
    image: postgres:13.3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5644:5644"
    restart: always
    networks:
      - scooter_bridge
  backend:
    container_name: backend_scooter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - scooter_bridge

networks:
  scooter_bridge:
    driver: bridge